backend:
  name: git-gateway
  branch: master

media_folder: "static/images"
public_folder: "/images"

collections:
  - name: "menu"
    identifier_field: name
    label: "Menu"
    folder: "cms_data"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Collection Type", name: "collectionType", widget: "hidden", default: "menu-entries" }
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Ingredients", name: "ingredients", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Price", name: "price", widget: "number", valueType: "int" }
